version: '3'
services:

  django:
    build: ./backend/django
    tty: true
    container_name: django-admin
    command: uwsgi --socket :8000 --module config.wsgi --py-autoreload 1 --logto /tmp/mylog.log
    volumes:
      - ./backend/django/src:/usr/src/django
    expose:
      - "8000"
    env_file:
      - ./backend/django/src/.env
  
  next:
    build: ./frontend/next
    container_name: next-admin
    command: sh -c 
      "npm run build ; npm run dev"
      #本番環境ではnpm run start
    tty: true
    volumes:
      - ./frontend/next:/usr/src/next
      - /usr/src/next/node_modules
    expose:
      - "3000"